name: Lean Action CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-core:
    name: Build Kraken (as per lean-toolchain)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1

  run-asm-tests:
    name: Run ASM tests (Ubuntu)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: leanprover/lean-action@v1
      - run: python3 Kraken/Test/asm_tests.py Kraken/Test/asm
