/-
Kraken AsmCompiler - Assembly to Lean Source Compiler

Converts x86_64 AT&T assembly strings into Lean source files containing
Program objects that can be directly evaluated with Kraken's `eval` function.

Uses Parser.parseOrEmpty for parsing and Lean's built-in `repr` for
generating valid Lean syntax.

Compatible with Lean 4.22.0+.
-/

import Kraken.Parser
import Kraken.Semantics

namespace Kraken.AsmCompiler

/-- Check if a line has data directives (like .quad, .space, etc.). -/
def hasDataDirective (line : String) : Bool :=
  let words := line.splitOn " "
  words.any fun w =>
    let t := w.trim
    t == ".quad" || t == ".space" || t == ".byte" || t == ".word" ||
    t == ".ascii" || t == ".long" || t == ".zero" ||
    t.startsWith ".quad" || t.startsWith ".space" || t.startsWith ".byte"

/-- Strip assembler directives that Kraken doesn't handle.
    Keeps instructions, labels (without directives), and comments. -/
def stripDirectives (asmCode : String) : String :=
  let lines := asmCode.splitOn "\n"
  let filtered := lines.filter fun line =>
    let trimmed := line.trim
    -- Keep empty lines and # comments (parser handles these)
    -- Skip // comments (C-style, parser doesn't handle)
    if trimmed.isEmpty || trimmed.startsWith "#" then true
    else if trimmed.startsWith "//" then false
    -- Skip lines starting with . (directives like .data, .text, .align, .globl)
    -- except .L labels (local labels)
    else if trimmed.startsWith "." then
      trimmed.startsWith ".L" && trimmed.length > 2 &&
        (trimmed.get ⟨2⟩).isAlphanum
    -- Skip data declarations: lines containing .quad, .space, .byte, etc.
    else if hasDataDirective trimmed then false
    -- Skip syscall instructions (not supported)
    else if trimmed == "syscall" then false
    -- Skip RIP-relative addressing (contains %rip) - not supported by parser
    else if (trimmed.splitOn "%rip").length > 1 then false
    -- Skip pushfq/popq (not supported by parser)
    else if trimmed.startsWith "pushfq" || trimmed.startsWith "popq" then false
    -- Skip jump to capture epilogue
    else if trimmed.startsWith "jmp" && (trimmed.splitOn "_kraken_capture").length > 1 then false
    else true
  String.intercalate "\n" filtered

/-- Strip capture epilogue code (everything after _kraken_capture:).
    This is test harness code that uses unsupported instructions. -/
def stripCaptureEpilogue (asmCode : String) : String :=
  let lines := asmCode.splitOn "\n"
  let (beforeEpilogue, _) := lines.foldl (fun (acc, seenEpilogue) line =>
    if seenEpilogue then (acc, true)
    else if line.trim == "_kraken_capture:" || line.trim.startsWith "_kraken_capture:" then
      (acc, true)
    else (acc ++ [line], false)
  ) ([], false)
  String.intercalate "\n" beforeEpilogue



/-- Generate Lean source file from assembly string.

    Arguments:
    - moduleName: Name for the generated module (used in comment)
    - defName: Name for the program definition
    - asmCode: Raw assembly code (will strip directives)

    Returns: Complete Lean source file as a string -/
def compileToLean (moduleName defName asmCode : String) : String :=
  let noEpilogue := stripCaptureEpilogue asmCode
  let cleaned := stripDirectives noEpilogue
  let prog := Parser.parseOrEmpty cleaned

  let progRepr := repr prog
  "/-\n  Auto-generated by Kraken AsmCompiler\n  Source: " ++ moduleName ++ "\n-/\n\nimport Kraken\n\ndef " ++ defName ++ " : Program := " ++ progRepr.pretty ++ "\n"

end Kraken.AsmCompiler
